### ISSUE TITLE
S-Update Method not allowed

### ISSUE THREAD

**Issue by Kakumi** [TheShark34/S-Update#11]
Salut, j'ai un soucis avec SUpdate, en local (xampp) j'ai aucun soucis, tout fonctionne mais une fois mis sur un hébegement web, j'ai une erreur lors de la mise à jour des fichiers :

`java.io.IOException: Server returned HTTP response code: 403 for URL: http://bootstrap.site.com/server/is-enabled
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at fr.theshark34.supdate.ServerRequester.send(ServerRequester.java:170)
	at fr.theshark34.supdate.ServerRequester.sendPostRequest(ServerRequester.java:100)
	at fr.theshark34.supdate.Updater.checkState(Updater.java:223)
	at fr.theshark34.supdate.Updater.start(Updater.java:111)
	at fr.theshark34.supdate.SUpdate.start(SUpdate.java:160)
	at mon.package.BootstrapMain.update(BootstrapMain.java:55)
	at mon.package.main(BootstrapMain.java:30)`

Cela pourrait être lié à quoi ?
Merci :)

**Comment by Litarvan** [comment]
Soit tu as mis le mauvais URL (le plus probable), soit ton hebergeur refuse le programme, en tout cas ça vient du site. Note, pour le bootstrap il faut remettre un **nouveau serveur** s-update dans le sous-dossier bootstrap/
